# Generated by Django 2.1.7 on 2019-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_rename_resource_class_to_resource_class_path'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='members', to='org.Organization'),
        ),
    ]
