# Generated by Django 2.1.7 on 2019-08-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_organizations'),
        ('users', '0007_emergency_contact_data'),
    ]

    operations = [
        migrations.RemoveField(model_name='member', name='address'),
        migrations.RemoveField(model_name='member', name='birth_date'),
        migrations.RemoveField(model_name='member', name='phone_number'),
        migrations.RemoveField(model_name='member', name='emergency_contact_name'),
        migrations.RemoveField(model_name='member', name='emergency_contact_number'),
    ]
