# Generated by Django 2.1.7 on 2019-08-23 21:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0005_userprofile_null_picture')]

    operations = [
        migrations.RemoveField(model_name='userprofile', name='picture_url'),
        migrations.RemoveField(model_name='userprofile', name='subject'),
        migrations.RemoveField(model_name='userprofile', name='user_type'),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True
            ),
        ),
    ]
