# Generated by Django 2.1.11 on 2019-08-27 13:54

from importlib import import_module

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations
from jwkest.jwt import JWT


def forward(apps, schema_editor):
    """Copy existing VMI social auth id_token payloads into the new UserProfile.id_token_payload field"""
    db = schema_editor.connection.alias
    UserProfile = import_module('apps.users.models').UserProfile
    for profile in UserProfile.objects.using(db).all():
        vmi = profile.user.social_auth.filter(provider='vmi').first()
        if vmi:
            id_token = vmi.extra_data.get('id_token')
            profile.id_token_payload = JWT().unpack(id_token).payload()
            profile.save()


class Migration(migrations.Migration):

    dependencies = [('users', '0007_emergency_contact_data')]

    operations = [migrations.RunPython(forward, lambda: None)]
