# Generated by Django 2.1.11 on 2019-09-18 20:51

from django.db import migrations
from django.contrib.auth import get_user_model
from apps.users.models import create_user_set_recovery_passphrase_notification


def forward(apps, schema_editor):
    """
    call the create_user_set_recovery_passphrase_notification trigger for all users,
    as though they were just created.
    """
    User = get_user_model()
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        create_user_set_recovery_passphrase_notification(
            User, user, True, db_alias=db_alias
        )


def reverse(apps, schema_editor):
    """
    delete password recovery notifications for all users
    """
    Notification = apps.get_model('notifications', 'notification')
    db_alias = schema_editor.connection.alias
    Notification.objects.using(db_alias).filter(
        type='user_set_recovery_passphrase'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emergency_contact_data'),
        ('notifications', '0004_notification_type'),
    ]

    operations = [migrations.RunPython(forward, reverse)]
