# Generated by Django 2.1.11 on 2019-10-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notify_users_set_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
