# Generated by Django 2.1.7 on 2019-03-12 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_orgresourceaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcegrant',
            options={'verbose_name_plural': 'Resource Grants'},
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
