# Generated by Django 2.1.7 on 2019-03-15 18:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_resourcegrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
