# Generated by Django 2.1.7 on 2019-03-15 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0003_organization_phone_and_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resource_class', models.CharField(choices=[('apps.sharemyhealth.resources.Resource', 'apps.sharemyhealth.resources.Resource')], default='apps.sharemyhealth.resources.Resource', max_length=255)),
                ('member', models.ForeignKey(help_text='The member who can grant this Organization access to the resource', on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests_received', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
                ('user', models.ForeignKey(help_text='The user at the Organization who initiated this request', on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resource Requests',
            },
        ),
    ]
