# Generated by Django 2.1.7 on 2019-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_auto_20190312_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcegrant',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourcegrant',
            name='provider_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='resourcegrant',
            name='resource_class',
            field=models.CharField(choices=[('apps.sharemyhealth.resources.Resource', 'apps.sharemyhealth.resources.Resource')], default=('apps.sharemyhealth.resources.Resource', 'apps.sharemyhealth.resources.Resource'), max_length=255),
        ),
    ]
