# Generated by Django 2.1.7 on 2019-03-18 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('org', '0004_resourcegrant_rename_user_to_member'),
        ('org', '0003_organization_phone_and_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'resource_class',
                    models.CharField(
                        choices=[
                            (
                                'apps.sharemyhealth.resources.Resource',
                                'apps.sharemyhealth.resources.Resource',
                            )
                        ],
                        default='apps.sharemyhealth.resources.Resource',
                        max_length=255,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('Requested', 'Requested'),
                            ('Approved', 'Approved'),
                            ('Denied', 'Denied'),
                        ],
                        default='Requested',
                        max_length=10,
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        help_text='The member who can grant this Organization access to the resource',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='resource_requests_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='org.Organization',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='The user at the Organization who initiated this request',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='resource_requests_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'verbose_name_plural': 'Resource Requests'},
        ),
        migrations.RenameField(
            model_name='resourcegrant', old_name='user', new_name='member'
        ),
        migrations.AlterField(
            model_name='resourcegrant',
            name='member',
            field=models.ForeignKey(
                help_text='The member who has granted this Organization access to the resource',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='resourcegrant',
            name='resource_request',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='org.ResourceRequest',
            ),
        ),
    ]
