# Generated by Django 2.1.7 on 2019-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20190312_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcegrant',
            name='provider_name',
        ),
        migrations.AlterField(
            model_name='resourcegrant',
            name='resource_class',
            field=models.CharField(choices=[('apps.sharemyhealth.resources.Resource', 'apps.sharemyhealth.resources.Resource')], default='apps.sharemyhealth.resources.Resource', max_length=255),
        ),
    ]
