# Generated by Django 2.1.7 on 2019-03-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_resourcerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegrant',
            name='resource_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.ResourceRequest'),
        ),
    ]
