# Generated by Django 2.1.7 on 2019-03-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('org', '0004_resourcerequest_and_resourcegrant')]

    operations = [
        migrations.RenameField(
            model_name='resourcegrant',
            old_name='resource_class',
            new_name='resource_class_path',
        ),
        migrations.RenameField(
            model_name='resourcerequest',
            old_name='resource_class',
            new_name='resource_class_path',
        ),
    ]
