# Generated by Django 2.1.7 on 2019-03-15 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20190315_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegrant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcegrant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
