# Generated by Django 2.1.7 on 2019-06-16 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('org', '0005_rename_resource_class_to_resource_class_path')]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='picture_url',
            field=models.TextField(
                blank=True,
                help_text="The URL of Organization's logo (from VMI)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.TextField(
                blank=True, help_text='Populated from VMI.', null=True
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Agents'
            ),
        ),
    ]
