# Generated by Django 2.1.7 on 2019-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_resourcegrant_resource_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Requested', max_length=10),
        ),
    ]
