# Generated by Django 2.1.7 on 2019-03-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_resourcerequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcegrant',
            old_name='user',
            new_name='member',
        ),
    ]
