# Generated by Django 2.1.7 on 2019-03-18 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_resourcegrant_rename_user_to_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegrant',
            name='member',
            field=models.ForeignKey(help_text='The member who has granted this Organization access to the resource', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
