# Generated by Django 2.1.11 on 2019-08-26 20:01

import logging
from importlib import import_module
from django.db import migrations

log = logging.getLogger(__name__)


def forward(apps, schema_editor):
    db = schema_editor.connection.alias
    Organization = apps.get_model('org', 'Organization')

    # 1. Copy org agent relationships from the Organization.users field.
    for org in Organization.objects.using(db).all():
        for user in org.users.using(db).all():
            org.agents.add(user)

    # 2. Copy org member relationships from Member.organizations
    try:
        Member = import_module('apps.member.models').Member
    except AttributeError:
        log.warn('The Member model has been removed, so Member.organizations will not be migrated')
        return

    # Copy org member relationships from the Member.organizations field.
    for member in Member.objects.using(db).all():
        for org in member.organizations.using(db).all():
            org.members.add(member.user)


def reverse(apps, schema_editor):
    raise NotImplementedError


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_org_members_agents_1_create_fields'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
