# Generated by Django 2.1.11 on 2019-08-29 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('org', '0009_org_members_agents_2_data')]

    operations = [
        migrations.AlterField(
            model_name='resourcegrant',
            name='member',
            field=models.ForeignKey(
                help_text='The member who has granted this Organization access to the resource',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resource_grants',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='resourcegrant',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resource_grants',
                to='org.Organization',
            ),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resource_requests',
                to='org.Organization',
            ),
        ),
    ]
